### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by LaplaceSingularity** [mariaKozlovtseva/Brain-tumor-via-MRI-detection#1]
Hey Maria,

I'm currently doing my last project for graduation, it's about brain tumors and I find your project very interesting. It's my first project with image processing, so I don't have experience.
Could you provide me these files too? Are not in that zip file and If I don't ask too much, could tell me where did you get "brain_MRI_models_weights"? 

classifier-resnet-weights_fine_tuning_16b_345_3.hdf5
model_fine_tuning_16b_345_3.json

**Comment by LaplaceSingularity** [comment]
I just realize that you created that file...but could tell me where did you get "brain_MRI_models_weights"?I'm just curios plus I need some references for my project.

**Comment by mariaKozlovtseva** [comment]
Hi! In readme I’ve added a link to google drive with this files

**Comment by LaplaceSingularity** [comment]
Thank you, Maria
